### ISSUE TITLE
Access to training data

### ISSUE THREAD

**Issue by mukesh-mehta** [avineshpvs/indic_tagger#3]
How can I access the training data used in the project??

**Comment by hyunlin** [comment]
same question +1

**Comment by ashispapu** [comment]
How to access the training data ? Any plan to make it public ?

**Comment by avineshpvs** [comment]
Hi Mukesh, Hyunlin, Ashispapu sorry for the delayed reply.

Well unfortunately the data is proprietary and is freely available for research purpose.
Please do contact folks from IIIT Hyderabad, LTRC lab, https://ltrc.iiit.ac.in/nlpmt/
